zone-eu/zone-mta

- lib/api-server.js
- lib/mail-queue.js
- lib/queue-locker.js
- lib/queue-server.js
- lib/sending-zone.js
> Refactored locking system

- README.md
- config/bounces.txt
- lib/api-server.js
- lib/bounces.js
- lib/iptools.js
- lib/mail-queue.js
- lib/queue-server.js
- lib/sender.js
- package.json
This update also includes a breaking change in naming queued keys
> Added new API method to list queued messages

- config/bounces.txt
- config/default.js
- lib/address-tools.js
- lib/mail-drop.js
- lib/sending-zone.js
- package.json
- test/address-tools-test.js
- test/ttl-cache-test.js
This allows to use IP warm-up as you can set a lower share ratio for new addresses
> Added option to share load between addresses unevenly

- config/bounces.txt
- lib/queue-server.js
- lib/sender.js
- package.json
The logged traffic does not include the message contents, only smtp commands and responses for debugging purposes
> Added option to log smtp traffic against specific hosts

- CHANGELOG.md
- config/default.js
- lib/api-server.js
- lib/mail-drop.js
- lib/mail-queue.js
- lib/queue-server.js
- lib/remote-queue.js
- lib/sender.js
- package.json
- test/queue-test.js
- test/ttl-cache-test.js
Turned out to be a huge mistake, clear everything as soon as possible
> Do not keep deleted messages around

- README.md
- lib/mail-queue.js
- plugins/README.md
- test/queue-test.js
This is needed to route individual recipients before storing recipient data to the queue database
Added note about ZoneMTA [Recovery tool](https://github.com/zone-eu/zone-mta-recover)
> Added new plugin hook queue:route

- lib/dkim-relaxed-body.js
- test/dkim-relaxed-body-test.js
Zero body should create null hash instead of '\r\n'
> Fixed DKIM body hash for empty body

- lib/sender.js
Hi, as suggested by ugorey I added the hook sender:delivered in the lib/sender.js file.
Please check that everything is ok.
Thanks a lot
> Fixes #168: Add sender:delivered hook

- config/bounces.txt
Following was matching yahoo rule and no Gmail rule, so updated those:
```
421-4.7.0 [1.2.3.4 15] Our system has detected an unusual rate of unsolicited mail originating from your IP address. To protect our users from spam, mail sent from your IP address has
```
And a greylist that looks like a block, but it's a greylist 😄
> Add gmail block and odd greylist bounces

- lib/smtp-interface.js
- plugins/README.md
Added a "smtp:connect" hook which give the ability to do e.g. a IP restriction check before any SMTP dialog is started.
Added hook 'sender:tlserror' to documentation
> Added new hook "smtp:connect"

- config/default.js
- lib/dkim-sign.js
- plugins/core/dkim.js
Make the headers to sign configurable. 
headerFields will overwrite the default headers
additionalHeaderField will append the headers to the default one
> DKIM: Configurable headers to sign

- lib/plugin-handler.js
- plugins/README.md
Let plugins register own API endpoints
> Plugin HTTP API

- config/default.js
- lib/connection-pool.js
- lib/sender.js
- lib/sending-zone.js
- services/sender.js
Implemented connection pooling. This work is based on your "shared-connections" branch. I've done a bit rework.
I tried also to implement a inter-process caching. But this didn't work reliable.
> Connection pooling

- lib/connection-pool.js
A little fix i pushed in the wrong branch so it was not in the original branch.
> Connection cleanup fix

- README.md
- lib/connection-pool.js
- lib/queue-server.js
- services/sender.js
Added the code which i used for collection the connection pool statistics. 
I kept the code universal so the "receiver" and/or the "sender" process can be extended to collect metrics.
> Connection pool prometheus metrics

- config/bounces.txt
Adding error from Comcast when IP is on what appears to be their private/internal RBL
> Updating bounces.txt

- config/bounces.txt
554 5.7.1 Rejected because Bad IP
> Add blacklist response

- config/bounces.txt
Additional blacklist responses added to bounces.txt
> adding in three new blacklist responses

- config/bounces.txt
- package-lock.json
- package.json
Fixed Outlook no-such-user bounce detection
> Fixed Outlook no-such-user bounce detection

- lib/sender.js
- package-lock.json
- package.json
- plugins/README.md
* Added new plugin hook `sender:responseError`
* allow configurable defer times
> feat(plugins): Added new plugin hook sender:responseError
