- config/bounces.txt
- lib/mail-queue.js
DELETE /messages/:id/ was timeouting and the following message was logged: "Third parameter to `find()` must be a callback or undefined". Also had to change `nextObject()` to `next()` in the cursor.
> Unable to delete a message using the API (from zmta-webadmin, for example)

- config/bounces.txt
IPTS04 error generated by Yahoo comes in invalid format (without SMTP error code prefix). Zonemta treats the error as unknown and rejects at first try. This is a temporary error and it should be retried.
> IPTS04 Yahoo smtp error fix

- lib/db.js
- lib/mail-queue.js
When there is a problem with the Redis connection, the error message says MongoDB:
```
ERR! Queue Could not initialize MongoDB: connect ECONNREFUSED 127.0.0.1:63799
```
To make it clearer, I suggest moving the log.error() and log.info() calls early in the callback and change the error message to a generic 'Could not initialize database'.
```
ERR! Redis/17626 connect ECONNREFUSED 127.0.0.1:63799
ERR! Queue Could not initialize database: connect ECONNREFUSED 127.0.0.1:63799
```
> Making it clearer when the DB connection problem is with Redis.

- config/bounces.txt
Identifying Trend MicroRBL+ blacklist. Example:
550 Service unavailable; Client Host [1.2.3.4] blocked using Trend Micro RBL+. Please see http://www.mail-abuse.com/cgi-bin/lookup?ip_address=1.2.3.4
> Adding Trend Micro RBL+ blacklist rejection to bounces.txt.

- lib/plugin-handler.js
Plugins fail to load on Windows because path separators are not respected.
> Fixes #174: plugins fail to load on Windows

- config/bounces.txt
Hornetsecurity was previously known as antispameurope and uses the cloud-security.net domain.
> Identifying when sender is blacklisted at hornetsecurity

- README.md
Newest node.js version (on ubuntu 18.04) requires npm init to create json.
Fix eslint dependencies warning.
> Add npm init and dependencies

- config/default.js
- lib/mail-queue.js
Made the default zone configurable. 
We had/have e.g. the case that we do not want to share the default zone but the other zones in the queue are shared.
> Make default zone configurable

- plugins/README.md
Make the plugin HTTP api doc more clear that there is currently no direct way to share data.
> Make plugin api doc clear

- config/bounces.txt
Fix O365 bounce message.
Saw `550 5.4.1 Recipient address rejected: Access denied. AS(201806281) [PR2FRA01FT009.eop-fra01.prod.protection.outlook.com]` in the wild.
> Fixed O365 bounce msg.

- lib/smtp-interface.js
This patch test the permission of a given cert file. The permissions checked if it is readable.
I had issue on this error 
```BASH
SERVERR error=140569775089536:error:1417A0C1:SSL routines:tls_post_process_client_hello:no shared cipher:../deps/openssl/openssl/ssl/statem/statem_srvr.c:2284:
```
There wasn't much helped on the log. As the certs have no problems running on other services such as haraka. Checked file path and verified the cert still zone-mta have problems loading it. After i debugged found out that somehow the file was denied to be read for zone-mta service. Quick fix with chown and and resolved it. Hopefully, this patch will save hours of debugging.
> Check for the accessibility of certs

- lib/mail-queue.js
- lib/queue-server.js
Some plugins can update the `sendingZone` of a message:
https://github.com/zone-eu/zone-mta/tree/master/plugins#updating-database-entries
The update is not applied to metadata too (GFS stored).
On the next delivery attempt from the **NEW** `sendingZone`, the `delivery` object passed to plugins has the **OLD** `sendingZone`.
This update fixes this issue.
> do not update delivery.sendingZone with metadata sendingZone

- lib/sender.js
This affects ACCEPTED, DEFERRED, and REJECTED logging updates from sender.js, and is useful when using log:entry to track the status of emails in plugins.
> Add messageId to the entry object when using remote log

- lib/api-server.js
- lib/mail-queue.js
Address entries in the suppression list are handled in lowercase at the
moment (mail-queue.js)
Ensure entries added via the api server are converted to lowercase.
Also ensure domain entries are handled in lowercase
> Handle suppression entries case-insensitive

- lib/sender.js
The connection key was using `delivery.zoneAddress` which is only there if IPv6 is disabled.
Now it is using the correct zone addresses.
> Fix connection pooling with IPv6

- lib/mail-queue.js
- lib/sender.js
This patch:
- adds the **sessionId** to the _delivery_ object.
- adds a log line to inform when all SMTP deliveries have done.
- adds the support of a new flag **delivery.isSuppressed** in case we want to use an external suppression engine and we don't want to delivery a specific message to a destination.
> Add sessionId to delivery object + handle delivery.isSuppressed flag

- lib/sender.js
This patch:
- adds the support of a new flag delivery.account.returnPathDomain in case we want to use a custom return path domain, defined per user, and we don't want to use the default hostname or delivery zone name.
> Add custom return path domain in delivery.account object

- README.md
- config/bounces.txt
- package-lock.json
- package.json
> Describe db fields

- lib/sender.js
Sending Zone class pulls ignoreTLS from config, but Sender did not use this value
Now it does
> Retrieve ignoreTLS value from Sending Zone, or default to false

- config/bounces.txt
There are several rules which refer to the category "envelope" but are not specified at the top of the list of categories that exist. I just added that category at the top so it's easy to refer to all possible categories that exist with ZoneMTA.
> Adding missing category "envelope"

- config/bounces.txt
Fixes mis-classification of 4.7.2x status code as mailing list expansion error
> Add word boundary when matching extended status codes

- README.md
- lib/queue-server.js
Hello,
I've added the zone-name to the `zonemta_delivery_status` metric. For the other counters, I've tried it, but did not succeeded in a timly manner. Please squash & merge if accepted.
> feat: add zone name to prometheus

- .github/workflows/test.yml
- lib/smtp-interface.js
if it is then do not allow new connections
fixes #309
> ZMS-247 onConnect hook check if server is already closing
